/joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05

/teleop_node:
  ros__parameters:
    axis_linear.x: 1
    axis_linear.y: 2
    axis_angular.yaw: 0
    axis_angular.roll: 3
    scale_linear.x: 0.4
    scale_linear.y: 0.4
    scale_linear.z: 0.2
    enable_button: 9
    enable_turbo_button: 7